server:
  port: 80

spring:
  main:
    web-application-type: reactive
    allow-circular-references: true
  application:
    name: api-gateway-service
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "http://localhost:3000"
            allowed-headers: "*"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        - id: email-schedule
          predicates:
            - Path=/email/**
          uri: http://localhost:9091
          filters:
            - AuthenticationFilter
        - id: auth-service
          predicates:
            - Path=/auth/**
          uri: http://localhost:9092
          filters:
            - AuthenticationFilter
