server:
  port: 80

spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway-service
  cloud:
    gateway:
      routes:
        - id: email-schedule
          predicates:
            - Path=/email/**
          uri: http://localhost:9091
          filters:
            - AuthenticationFilter
        - id: auth-service
          predicates:
            - Path=/auth/**
          uri: http://localhost:9092
          filters:
            - AuthenticationFilter
